services:
  - type: web
    name: thief-police-captcha
    env: static
    buildCommand: |
      echo "Node.js version: $(node -v)"
      echo "NPM version: $(npm -v)"
      npm install
      npm run build
    staticPublishPath: ./dist
    nodeVersion: 18.20.2
    envVars:
      - key: NODE_VERSION
        value: 18.20.2
