services:
  - type: web
    name: thief-police-captcha
    env: static
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    build:
      nodeVersion: 20.19.0
