services:
  - type: web
    name: thief-police-captcha
    env: static
    buildCommand: |
      cd thief-police-captcha
      npm install
      npm run build
    startCommand: npm run preview -- --host
    staticPublishPath: ./thief-police-captcha/dist
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
