services:
  - type: static
    name: thief-police-captcha
    env: node
    buildCommand: |
      cd thief-police-captcha
      npm install
      npm run build
    staticPublishPath: ./thief-police-captcha/dist
    routes:
      - type: rewrite
        source: '/*'
        destination: '/index.html'
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: NPM_CONFIG_PRODUCTION
        value: 'false'
